[package]
name = "kd6-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kd6-core = { path = "../kd6-core" }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
sha2 = "0.10"
